skins.1=2
name.1=iregex:.*(blossom|cherry).*

skins.2=3
name.2=iregex:.*(decay).*

skins.3=4
name.3=iregex:.*(herobrine).*

skins.4=5
name.4=iregex:.*(lasagna).*

skins.5=6
name.5=iregex:.*(jolly).*

skins.6=7
name.6=iregex:.*(bloodsucker).*

skins.7=9
name.7=iregex:.*(clover).*

skins.8=10
name.8=iregex:.*(kittyuh|kitty).*

skins.9=11
name.9=iregex:.*(goldie).*


skins.10=1 2 3 4 5 6 7 8 9 10 11
weights.10=80 0 0 0 0 0 0 20 0 0 0



