/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  net.minecraft.class_3414
 */
package backported.updates.content.client.registries;

import backported.updates.content.core.FeatureFlag;
import backported.updates.foundation.core.helper.SoundRegistry;
import java.util.Optional;
import java.util.function.Supplier;
import net.minecraft.class_3414;

public class ModSoundEvents {
    public static final SoundRegistry SOUNDS = SoundRegistry.create("minecraft");
    public static final Supplier<class_3414> EYEBLOSSOM_OPEN_LONG = SOUNDS.soundEvent("block.eyeblossom.open_long");
    public static final Supplier<class_3414> EYEBLOSSOM_OPEN = SOUNDS.soundEvent("block.eyeblossom.open");
    public static final Supplier<class_3414> EYEBLOSSOM_CLOSE_LONG = SOUNDS.soundEvent("block.eyeblossom.close_long");
    public static final Supplier<class_3414> EYEBLOSSOM_CLOSE = SOUNDS.soundEvent("block.eyeblossom.close");
    public static final Supplier<class_3414> EYEBLOSSOM_IDLE = SOUNDS.soundEvent("block.eyeblossom.idle");
    public static final Supplier<class_3414> PALE_HANGING_MOSS_IDLE = SOUNDS.soundEvent("block.pale_hanging_moss.idle");
    public static final Supplier<class_3414> CREAKING_HEART_BREAK = SOUNDS.soundEvent("block.creaking_heart.break");
    public static final Supplier<class_3414> CREAKING_HEART_FALL = SOUNDS.soundEvent("block.creaking_heart.fall");
    public static final Supplier<class_3414> CREAKING_HEART_HIT = SOUNDS.soundEvent("block.creaking_heart.hit");
    public static final Supplier<class_3414> CREAKING_HEART_HURT = SOUNDS.soundEvent("block.creaking_heart.hurt");
    public static final Supplier<class_3414> CREAKING_HEART_PLACE = SOUNDS.soundEvent("block.creaking_heart.place");
    public static final Supplier<class_3414> CREAKING_HEART_STEP = SOUNDS.soundEvent("block.creaking_heart.step");
    public static final Supplier<class_3414> CREAKING_HEART_IDLE = SOUNDS.soundEvent("block.creaking_heart.idle");
    public static final Supplier<class_3414> CREAKING_HEART_SPAWN = SOUNDS.soundEvent("block.creaking_heart.spawn");
    public static final Supplier<class_3414> RESIN_BREAK = SOUNDS.soundEvent("block.resin.break");
    public static final Supplier<class_3414> RESIN_FALL = SOUNDS.soundEvent("block.resin.fall");
    public static final Supplier<class_3414> RESIN_PLACE = SOUNDS.soundEvent("block.resin.place");
    public static final Supplier<class_3414> RESIN_STEP = SOUNDS.soundEvent("block.resin.step");
    public static final Supplier<class_3414> RESIN_BRICKS_BREAK = SOUNDS.soundEvent("block.resin_bricks.break");
    public static final Supplier<class_3414> RESIN_BRICKS_FALL = SOUNDS.soundEvent("block.resin_bricks.fall");
    public static final Supplier<class_3414> RESIN_BRICKS_HIT = SOUNDS.soundEvent("block.resin_bricks.hit");
    public static final Supplier<class_3414> RESIN_BRICKS_PLACE = SOUNDS.soundEvent("block.resin_bricks.place");
    public static final Supplier<class_3414> RESIN_BRICKS_STEP = SOUNDS.soundEvent("block.resin_bricks.step");
    public static final Supplier<class_3414> DRIED_GHAST_BREAK = SOUNDS.soundEvent("block.dried_ghast.break");
    public static final Supplier<class_3414> DRIED_GHAST_STEP = SOUNDS.soundEvent("block.dried_ghast.step");
    public static final Supplier<class_3414> DRIED_GHAST_FALL = SOUNDS.soundEvent("block.dried_ghast.fall");
    public static final Supplier<class_3414> DRIED_GHAST_AMBIENT = SOUNDS.soundEvent("block.dried_ghast.ambient");
    public static final Supplier<class_3414> DRIED_GHAST_AMBIENT_WATER = SOUNDS.soundEvent("block.dried_ghast.ambient_water");
    public static final Supplier<class_3414> DRIED_GHAST_PLACE = SOUNDS.soundEvent("block.dried_ghast.place");
    public static final Supplier<class_3414> DRIED_GHAST_PLACE_IN_WATER = SOUNDS.soundEvent("block.dried_ghast.place_in_water");
    public static final Supplier<class_3414> DRIED_GHAST_TRANSITION = SOUNDS.soundEvent("block.dried_ghast.transition");
    public static final Supplier<class_3414> LEAF_LITTER_BREAK = SOUNDS.soundEvent("block.leaf_litter.break");
    public static final Supplier<class_3414> LEAF_LITTER_STEP = SOUNDS.soundEvent("block.leaf_litter.step");
    public static final Supplier<class_3414> LEAF_LITTER_PLACE = SOUNDS.soundEvent("block.leaf_litter.place");
    public static final Supplier<class_3414> LEAF_LITTER_HIT = SOUNDS.soundEvent("block.leaf_litter.hit");
    public static final Supplier<class_3414> LEAF_LITTER_FALL = SOUNDS.soundEvent("block.leaf_litter.fall");
    public static final Supplier<class_3414> CACTUS_FLOWER_BREAK = SOUNDS.soundEvent("block.cactus_flower.break");
    public static final Supplier<class_3414> CACTUS_FLOWER_PLACE = SOUNDS.soundEvent("block.cactus_flower.place");
    public static final Supplier<class_3414> FIREFLY_BUSH_IDLE = SOUNDS.soundEvent("block.firefly_bush.idle");
    public static final Supplier<class_3414> SAND_IDLE = SOUNDS.soundEvent("block.sand.idle");
    public static final Supplier<class_3414> DEAD_BUSH_IDLE = SOUNDS.soundEvent("block.deadbush.idle");
    public static final Supplier<class_3414> DRY_GRASS = SOUNDS.soundEvent("block.dry_grass.ambient");
    public static final Optional<Supplier<class_3414>> COPPER_CHEST_CLOSE = ModSoundEvents.conditional("block.copper_chest.close", FeatureFlag.COPPER_AGE);
    public static final Optional<Supplier<class_3414>> COPPER_CHEST_OPEN = ModSoundEvents.conditional("block.copper_chest.open", FeatureFlag.COPPER_AGE);
    public static final Optional<Supplier<class_3414>> COPPER_CHEST_WEATHERED_CLOSE = ModSoundEvents.conditional("block.copper_chest_weathered.close", FeatureFlag.COPPER_AGE);
    public static final Optional<Supplier<class_3414>> COPPER_CHEST_WEATHERED_OPEN = ModSoundEvents.conditional("block.copper_chest_weathered.open", FeatureFlag.COPPER_AGE);
    public static final Optional<Supplier<class_3414>> COPPER_CHEST_OXIDIZED_CLOSE = ModSoundEvents.conditional("block.copper_chest_oxidized.close", FeatureFlag.COPPER_AGE);
    public static final Optional<Supplier<class_3414>> COPPER_CHEST_OXIDIZED_OPEN = ModSoundEvents.conditional("block.copper_chest_oxidized.open", FeatureFlag.COPPER_AGE);
    public static final Optional<Supplier<class_3414>> COPPER_GOLEM_STATUE_BREAK = ModSoundEvents.conditional("block.copper_golem_statue.break", FeatureFlag.COPPER_AGE);
    public static final Optional<Supplier<class_3414>> COPPER_GOLEM_STATUE_PLACE = ModSoundEvents.conditional("block.copper_golem_statue.place", FeatureFlag.COPPER_AGE);
    public static final Optional<Supplier<class_3414>> COPPER_GOLEM_STATUE_HIT = ModSoundEvents.conditional("block.copper_golem_statue.hit", FeatureFlag.COPPER_AGE);
    public static final Optional<Supplier<class_3414>> COPPER_GOLEM_STATUE_STEP = ModSoundEvents.conditional("block.copper_golem_statue.step", FeatureFlag.COPPER_AGE);
    public static final Optional<Supplier<class_3414>> COPPER_GOLEM_STATUE_FALL = ModSoundEvents.conditional("block.copper_golem_statue.fall", FeatureFlag.COPPER_AGE);
    public static final Supplier<class_3414> BUNDLE_INSERT_FAIL = SOUNDS.soundEvent("item.bundle.insert_fail");
    public static final Supplier<class_3414> CREAKING_AMBIENT = SOUNDS.soundEvent("entity.creaking.ambient");
    public static final Supplier<class_3414> CREAKING_ACTIVATE = SOUNDS.soundEvent("entity.creaking.activate");
    public static final Supplier<class_3414> CREAKING_DEACTIVATE = SOUNDS.soundEvent("entity.creaking.deactivate");
    public static final Supplier<class_3414> CREAKING_ATTACK = SOUNDS.soundEvent("entity.creaking.attack");
    public static final Supplier<class_3414> CREAKING_DEATH = SOUNDS.soundEvent("entity.creaking.death");
    public static final Supplier<class_3414> CREAKING_STEP = SOUNDS.soundEvent("entity.creaking.step");
    public static final Supplier<class_3414> CREAKING_FREEZE = SOUNDS.soundEvent("entity.creaking.freeze");
    public static final Supplier<class_3414> CREAKING_UNFREEZE = SOUNDS.soundEvent("entity.creaking.unfreeze");
    public static final Supplier<class_3414> CREAKING_SPAWN = SOUNDS.soundEvent("entity.creaking.spawn");
    public static final Supplier<class_3414> CREAKING_SWAY = SOUNDS.soundEvent("entity.creaking.sway");
    public static final Supplier<class_3414> CREAKING_TWITCH = SOUNDS.soundEvent("entity.creaking.twitch");
    public static final Supplier<class_3414> GHASTLING_AMBIENT = SOUNDS.soundEvent("entity.ghastling.ambient");
    public static final Supplier<class_3414> GHASTLING_DEATH = SOUNDS.soundEvent("entity.ghastling.death");
    public static final Supplier<class_3414> GHASTLING_HURT = SOUNDS.soundEvent("entity.ghastling.hurt");
    public static final Supplier<class_3414> GHASTLING_SPAWN = SOUNDS.soundEvent("entity.ghastling.spawn");
    public static final Supplier<class_3414> HAPPY_GHAST_AMBIENT = SOUNDS.soundEvent("entity.happy_ghast.ambient");
    public static final Supplier<class_3414> HAPPY_GHAST_DEATH = SOUNDS.soundEvent("entity.happy_ghast.death");
    public static final Supplier<class_3414> HAPPY_GHAST_HURT = SOUNDS.soundEvent("entity.happy_ghast.hurt");
    public static final Supplier<class_3414> HAPPY_GHAST_RIDING = SOUNDS.soundEvent("entity.happy_ghast.riding");
    public static final Supplier<class_3414> HARNESS_EQUIP = SOUNDS.soundEvent("entity.happy_ghast.equip");
    public static final Supplier<class_3414> HARNESS_UNEQUIP = SOUNDS.soundEvent("entity.happy_ghast.unequip");
    public static final Supplier<class_3414> HARNESS_GOGGLES_UP = SOUNDS.soundEvent("entity.happy_ghast.harness_goggles_up");
    public static final Supplier<class_3414> HARNESS_GOGGLES_DOWN = SOUNDS.soundEvent("entity.happy_ghast.harness_goggles_down");
    public static final Supplier<class_3414> PARROT_IMITATE_CREAKING = SOUNDS.soundEvent("entity.parrot.imitate.creaking");
    public static final Supplier<class_3414> WOLF_PUGLIN_AMBIENT = SOUNDS.soundEvent("entity.wolf_puglin.ambient");
    public static final Supplier<class_3414> WOLF_PUGLIN_DEATH = SOUNDS.soundEvent("entity.wolf_puglin.death");
    public static final Supplier<class_3414> WOLF_PUGLIN_GROWL = SOUNDS.soundEvent("entity.wolf_puglin.growl");
    public static final Supplier<class_3414> WOLF_PUGLIN_HURT = SOUNDS.soundEvent("entity.wolf_puglin.hurt");
    public static final Supplier<class_3414> WOLF_PUGLIN_PANT = SOUNDS.soundEvent("entity.wolf_puglin.pant");
    public static final Supplier<class_3414> WOLF_PUGLIN_WHINE = SOUNDS.soundEvent("entity.wolf_puglin.whine");
    public static final Supplier<class_3414> WOLF_SAD_AMBIENT = SOUNDS.soundEvent("entity.wolf_sad.ambient");
    public static final Supplier<class_3414> WOLF_SAD_DEATH = SOUNDS.soundEvent("entity.wolf_sad.death");
    public static final Supplier<class_3414> WOLF_SAD_GROWL = SOUNDS.soundEvent("entity.wolf_sad.growl");
    public static final Supplier<class_3414> WOLF_SAD_HURT = SOUNDS.soundEvent("entity.wolf_sad.hurt");
    public static final Supplier<class_3414> WOLF_SAD_PANT = SOUNDS.soundEvent("entity.wolf_sad.pant");
    public static final Supplier<class_3414> WOLF_SAD_WHINE = SOUNDS.soundEvent("entity.wolf_sad.whine");
    public static final Supplier<class_3414> WOLF_ANGRY_AMBIENT = SOUNDS.soundEvent("entity.wolf_angry.ambient");
    public static final Supplier<class_3414> WOLF_ANGRY_DEATH = SOUNDS.soundEvent("entity.wolf_angry.death");
    public static final Supplier<class_3414> WOLF_ANGRY_GROWL = SOUNDS.soundEvent("entity.wolf_angry.growl");
    public static final Supplier<class_3414> WOLF_ANGRY_HURT = SOUNDS.soundEvent("entity.wolf_angry.hurt");
    public static final Supplier<class_3414> WOLF_ANGRY_PANT = SOUNDS.soundEvent("entity.wolf_angry.pant");
    public static final Supplier<class_3414> WOLF_ANGRY_WHINE = SOUNDS.soundEvent("entity.wolf_angry.whine");
    public static final Supplier<class_3414> WOLF_GRUMPY_AMBIENT = SOUNDS.soundEvent("entity.wolf_grumpy.ambient");
    public static final Supplier<class_3414> WOLF_GRUMPY_DEATH = SOUNDS.soundEvent("entity.wolf_grumpy.death");
    public static final Supplier<class_3414> WOLF_GRUMPY_GROWL = SOUNDS.soundEvent("entity.wolf_grumpy.growl");
    public static final Supplier<class_3414> WOLF_GRUMPY_HURT = SOUNDS.soundEvent("entity.wolf_grumpy.hurt");
    public static final Supplier<class_3414> WOLF_GRUMPY_PANT = SOUNDS.soundEvent("entity.wolf_grumpy.pant");
    public static final Supplier<class_3414> WOLF_GRUMPY_WHINE = SOUNDS.soundEvent("entity.wolf_grumpy.whine");
    public static final Supplier<class_3414> WOLF_BIG_AMBIENT = SOUNDS.soundEvent("entity.wolf_big.ambient");
    public static final Supplier<class_3414> WOLF_BIG_DEATH = SOUNDS.soundEvent("entity.wolf_big.death");
    public static final Supplier<class_3414> WOLF_BIG_GROWL = SOUNDS.soundEvent("entity.wolf_big.growl");
    public static final Supplier<class_3414> WOLF_BIG_HURT = SOUNDS.soundEvent("entity.wolf_big.hurt");
    public static final Supplier<class_3414> WOLF_BIG_PANT = SOUNDS.soundEvent("entity.wolf_big.pant");
    public static final Supplier<class_3414> WOLF_BIG_WHINE = SOUNDS.soundEvent("entity.wolf_big.whine");
    public static final Supplier<class_3414> WOLF_CUTE_AMBIENT = SOUNDS.soundEvent("entity.wolf_cute.ambient");
    public static final Supplier<class_3414> WOLF_CUTE_DEATH = SOUNDS.soundEvent("entity.wolf_cute.death");
    public static final Supplier<class_3414> WOLF_CUTE_GROWL = SOUNDS.soundEvent("entity.wolf_cute.growl");
    public static final Supplier<class_3414> WOLF_CUTE_HURT = SOUNDS.soundEvent("entity.wolf_cute.hurt");
    public static final Supplier<class_3414> WOLF_CUTE_PANT = SOUNDS.soundEvent("entity.wolf_cute.pant");
    public static final Supplier<class_3414> WOLF_CUTE_WHINE = SOUNDS.soundEvent("entity.wolf_cute.whine");
    public static final Optional<Supplier<class_3414>> COPPER_GOLEM_STEP = ModSoundEvents.conditional("entity.copper_golem.step", FeatureFlag.COPPER_AGE);
    public static final Optional<Supplier<class_3414>> COPPER_GOLEM_HURT = ModSoundEvents.conditional("entity.copper_golem.hurt", FeatureFlag.COPPER_AGE);
    public static final Optional<Supplier<class_3414>> COPPER_GOLEM_DEATH = ModSoundEvents.conditional("entity.copper_golem.death", FeatureFlag.COPPER_AGE);
    public static final Optional<Supplier<class_3414>> COPPER_GOLEM_WEATHERED_STEP = ModSoundEvents.conditional("entity.copper_golem_weathered.step", FeatureFlag.COPPER_AGE);
    public static final Optional<Supplier<class_3414>> COPPER_GOLEM_WEATHERED_HURT = ModSoundEvents.conditional("entity.copper_golem_weathered.hurt", FeatureFlag.COPPER_AGE);
    public static final Optional<Supplier<class_3414>> COPPER_GOLEM_WEATHERED_DEATH = ModSoundEvents.conditional("entity.copper_golem_weathered.death", FeatureFlag.COPPER_AGE);
    public static final Optional<Supplier<class_3414>> COPPER_GOLEM_OXIDIZED_STEP = ModSoundEvents.conditional("entity.copper_golem_oxidized.step", FeatureFlag.COPPER_AGE);
    public static final Optional<Supplier<class_3414>> COPPER_GOLEM_OXIDIZED_HURT = ModSoundEvents.conditional("entity.copper_golem_oxidized.hurt", FeatureFlag.COPPER_AGE);
    public static final Optional<Supplier<class_3414>> COPPER_GOLEM_OXIDIZED_DEATH = ModSoundEvents.conditional("entity.copper_golem_oxidized.death", FeatureFlag.COPPER_AGE);
    public static final Optional<Supplier<class_3414>> COPPER_GOLEM_SPIN = ModSoundEvents.conditional("entity.copper_golem.spin", FeatureFlag.COPPER_AGE);
    public static final Optional<Supplier<class_3414>> COPPER_GOLEM_WEATHERED_SPIN = ModSoundEvents.conditional("entity.copper_golem_weathered.spin", FeatureFlag.COPPER_AGE);
    public static final Optional<Supplier<class_3414>> COPPER_GOLEM_OXIDIZED_SPIN = ModSoundEvents.conditional("entity.copper_golem_oxidized.spin", FeatureFlag.COPPER_AGE);
    public static final Optional<Supplier<class_3414>> COPPER_GOLEM_ITEM_GET = ModSoundEvents.conditional("entity.copper_golem.no_item_get", FeatureFlag.COPPER_AGE);
    public static final Optional<Supplier<class_3414>> COPPER_GOLEM_ITEM_NO_GET = ModSoundEvents.conditional("entity.copper_golem.no_item_no_get", FeatureFlag.COPPER_AGE);
    public static final Optional<Supplier<class_3414>> COPPER_GOLEM_ITEM_DROP = ModSoundEvents.conditional("entity.copper_golem.item_drop", FeatureFlag.COPPER_AGE);
    public static final Optional<Supplier<class_3414>> COPPER_GOLEM_ITEM_NO_DROP = ModSoundEvents.conditional("entity.copper_golem.item_no_drop", FeatureFlag.COPPER_AGE);
    public static final Optional<Supplier<class_3414>> COPPER_GOLEM_BECOME_STATUE = ModSoundEvents.conditional("entity.copper_golem_become_statue", FeatureFlag.COPPER_AGE);
    public static final Optional<Supplier<class_3414>> COPPER_GOLEM_SPAWN = ModSoundEvents.conditional("entity.copper_golem.spawn", FeatureFlag.COPPER_AGE);
    public static final Optional<Supplier<class_3414>> COPPER_GOLEM_SHEAR = ModSoundEvents.conditional("entity.copper_golem.shear", FeatureFlag.COPPER_AGE);
    public static final Supplier<class_3414> MUSIC_DISC_TEARS = SOUNDS.soundEvent("music_disc.tears");
    public static final Supplier<class_3414> MUSIC_DISC_LAVA_CHICKEN = SOUNDS.soundEvent("music_disc.lava_chicken");

    private static Optional<Supplier<class_3414>> conditional(String id, FeatureFlag flag) {
        return flag.isEnabled() ? Optional.of(SOUNDS.soundEvent(id)) : Optional.empty();
    }
}

